### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by SullyMan71** [NaJeongMo/Colaboratory-Notebook-for-Ultimate-Vocal-Remover#3]
Window size: 320
Model: HP2-4BAND-3090_4band_arch-500m_2
Parameter: 4band_44100
Aggressiveness: 0.09
High end process: mirroring2
TTA: True
Deep Extraction: False

loading model... done
stft of wave source... Traceback (most recent call last):
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 307, in <module>
    main()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 302, in main
    process.inference()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 94, in inference
    X_spec_m, input_high_end_h, input_high_end = spec_utils.loadWave(self.input, mp, hep=self.hep)
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/lib/spec_utils.py", line 14, in loadWave
    X_wave[bands_n+1], _ = librosa.load(
TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given
Notebook took: 8.3s

**Comment by Yukinoshita-Yukinoe** [comment]
I'm facing the same issue, have you managed to solve it yet?

**Comment by maolex** [comment]
Facing the same issue on Google Colab:

with HP-4BAND-V2_arch-124m.pth
loading model... done
stft of wave source... Traceback (most recent call last):
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 307, in <module>
    main()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 293, in main
    multi_file(useModel, args.input)
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 244, in multi_file
    process.inference()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 94, in inference
    X_spec_m, input_high_end_h, input_high_end = spec_utils.loadWave(self.input, mp, hep=self.hep)
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/lib/spec_utils.py", line 14, in loadWave
    X_wave[bands_n+1], _ = librosa.load(
TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given
Notebook took: 32.9s

**Comment by SullyMan71** [comment]
A Google Colab update must've broken something.

**Comment by dviralfi** [comment]
Something to do with arguments that spec_utils.py is taking . can't really understand the code :\

**Comment by rodrigogithub1** [comment]
I was having the same problem, but found a solution on Discord (posted by _Gosmokeless28_)

> Put `!pip install librosa==0.9.1` in the audio separation cell of the UVR 5.2 Colab notebook

I did it and now it works. I had to copy the Colab project first, to be able to edit the code. Then I added a new code under the first cell (under the cell where you mount your GDrive account) and included the pip install code mentioned.
Also, upon running the first cell, I checked the box "**ForceUpdate**", which I think pulls the latest version of the git project, I guess that's important too. It works!
