### ISSUE TITLE
Error message about cfloat

### ISSUE THREAD

**Issue by fu-wen-bin** [NaJeongMo/Colaboratory-Notebook-for-Ultimate-Vocal-Remover#8]
**I got this and i don't know how to do about that, Please help:**
```
loading model... done
stft of wave source... done
100% 83/83 [00:41<00:00,  2.01it/s]
100% 84/84 [00:43<00:00,  1.94it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 307, in <module>
    main()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 302, in main
    process.inference()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 122, in inference
    y_wave = spec_utils.cmb_spectrogram_to_wave(y_spec_m, mp, input_high_end_h, input_high_end_)  
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/lib/spec_utils.py", line 340, in cmb_spectrogram_to_wave
    wave = librosa.resample(spectrogram_to_wave(spec_s, bp['hl'], mp, False), bp['sr'], sr, res_type="sinc_fastest")
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/lib/spec_utils.py", line 297, in spectrogram_to_wave
    wave_left = librosa.istft(spec_left, hop_length=hop_length)
  File "/usr/local/lib/python3.10/dist-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py", line 394, in istft
    dtype = util.dtype_c2r(stft_matrix.dtype)
  File "/usr/local/lib/python3.10/dist-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/librosa/util/utils.py", line 2185, in dtype_c2r
    np.dtype(complex): np.dtype(np.float).type,
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself.
Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
Notebook took: 112.1s
```

**Comment by ValentyneMu** [comment]
Me too! Plz help ;(

**Comment by imjakedeason** [comment]
I'm getting the same error. Does anyone know how to fix it?
